Whisper Fix
Jaseci-Labs/jaseci pull request #1022
Opened 2023-03-23 15:24 UTC by chandralegend

2023-03-24 14:22 UTC, ypkang requested changes

2023-03-24 14:22 UTC, ypkang commented on jaseci_ai_kit/jac_speech/jac_speech/stt/stt.py
> +):
Lets add np array as an input option.

2023-03-24 14:22 UTC, ypkang commented on jaseci_ai_kit/jac_speech/jac_speech/stt/requirements.txt
> +openai-whisper
Make sure we have closed version requirements.

2023-03-24 14:22 UTC, ypkang commented on jaseci_ai_kit/jac_speech/jac_speech/stt/requirements.txt
> +openai-whisper
Make sure we have closed version requirements.

2023-03-31 17:28 UTC, chandralegend commented
@ypkang STT works well in remote as well

2023-03-31 19:07 UTC, ypkang approved these changes

2023-03-31 19:07 UTC, merged