New Module: Generate Embedding (gen_emb)
Jaseci-Labs/jaseci pull request #1199
Opened 2023-07-27 14:45 UTC by AshishMahendra

2023-07-27 16:11 UTC, ypkang requested changes

2023-07-27 16:11 UTC, ypkang commented on jaseci_ai_kit/jac_nlp/jac_nlp/gen_emb/gen_emb.py
> +    module = __import__(module_path, fromlist=[embeddings_function, setup_function])
We shouldn't import the module as part of the generate_embedding call since it can slow down a lot. Maybe we can move import to a `setup` call?

2023-07-27 16:11 UTC, ypkang commented on jaseci_ai_kit/jac_nlp/jac_nlp/gen_emb/gen_emb.py
> +    setup_function()  # Setup the selected module
same here. we should do this in  `setup`

2023-07-28 14:44 UTC, AshishMahendra commented on jaseci_ai_kit/jac_nlp/jac_nlp/gen_emb/gen_emb.py
> +    module = __import__(module_path, fromlist=[embeddings_function, setup_function])
updated

2023-07-28 14:44 UTC, AshishMahendra commented on jaseci_ai_kit/jac_nlp/jac_nlp/gen_emb/gen_emb.py
> +    setup_function()  # Setup the selected module
updated

2024-04-23 19:01 UTC, closed without merging