Fix: namespace problem in monitoring document
Jaseci-Labs/jaseci pull request #122
Opened 2022-03-08 02:46 UTC by Gorgeous-Patrick

I think that at this point, the document has completely given up teaching people to establish prometheus in a namespace. 
Fix:
1. Deleted '-n prometheus' param in the commands given completely.
2. \<xxx\> is considered a macro substitution in markdown and we did not define \<namespace\> macro. So it is ignored. I replaced it with \\\<namespace\\\> and added some comments about the usage.

2022-03-08 19:30 UTC, ypkang requested changes
@Gorgeous-Patrick good changes! Just one tiny thing to fix. I left comment on the line.

2022-03-08 19:30 UTC, ypkang commented on support/monitoring/grafana/grafana.yaml
> +      # url: http://localhost:8080
Remove this commented line.

2022-03-09 21:08 UTC, Gorgeous-Patrick commented on support/monitoring/grafana/grafana.yaml
> +      # url: http://localhost:8080
Resolved

2022-03-09 21:16 UTC, ypkang approved these changes
LGTM

2022-03-09 21:16 UTC, merged