Correction
Jaseci-Labs/jaseci pull request #1293
Opened 2024-09-16 12:46 UTC by Thamirawaran

## **Description**
disengage command added in visit_statements.jac to prevent overflow and  typo error (flaot -> float) in match_patterns.jac corrected

2024-10-10 12:05 UTC, Jayanaka-98 commented on jac/examples/data_spatial/custom_edge.jac
Show how we can filter by edge attributes.

2024-10-10 12:06 UTC, Jayanaka-98 commented on jac/examples/data_spatial/define_walker.jac
> +    root +:a:+> Start;
Huse 'here' instead of root

2024-10-10 12:10 UTC, Jayanaka-98 commented on jac/examples/data_spatial/filtering.jac
filtering by node attributes should be also included

2024-10-10 21:18 UTC, Jayanaka-98 requested changes

2024-10-10 21:18 UTC, Jayanaka-98 commented on jac/support/jac-lang.org/mkdocs.yml
Remove the reference.md if form yml if it is empty. After completing that add it later in a seperetare PR

2024-10-14 08:41 UTC, kugesan1105 approved these changes
This is good to merge.

2024-10-14 08:42 UTC, kugesan1105 commented on jac/support/jac-lang.org/mkdocs.yml
done!

2024-10-15 12:45 UTC, marsninja approved these changes

2024-10-15 12:45 UTC, marsninja commented
Nice work @Thamirawaran !!!

2024-10-15 12:48 UTC, merged