Fixing minor issues in Tutorial EECS449
Jaseci-Labs/jaseci pull request #1314
Opened 2024-09-25 12:28 UTC by TharukaCkasthuri

## **Description**

2024-10-04 21:56 UTC, ChrisIsKing requested changes

2024-10-04 21:56 UTC, ChrisIsKing commented on jac/support/jac-lang.org/docs/learn/tutorial/2_building-a-rag-chatbot.md
> +- `mtllm`: A toolkit for multi-task learning with language models.
I don't think this an accurate description of MTLLM 🤔

2024-10-04 21:56 UTC, ChrisIsKing commented on jac/support/jac-lang.org/docs/learn/tutorial/2_building-a-rag-chatbot.md
> +Begin by creating a file named `client.jac`. This file will define the frontend logic for interacting with users and displaying responses from the chatbot.
Change to "for interacting with the chatbot" or "for users to interact with the chatbot"

2024-10-04 21:56 UTC, ChrisIsKing commented on jac/support/jac-lang.org/docs/learn/tutorial/2_building-a-rag-chatbot.md
> +Now we handle the interaction with the backend server. After capturing the user's input, it will send to the backend, retrieve the assistant's response, and display it,
"It will forward this message to the backend, ...."

2024-10-04 21:56 UTC, ChrisIsKing commented on jac/support/jac-lang.org/docs/learn/tutorial/2_building-a-rag-chatbot.md
> +Lastly, we'll define the entry point of our program. Think about the `main` function of a python program. Here we authenticates the user and retrieves the token needed for the `bootstrap_frontend` fu
"authenticate"

2024-10-04 21:56 UTC, ChrisIsKing commented on jac/support/jac-lang.org/docs/learn/tutorial/code/server.jac
> +        visit [-->](`?Router) else {
@TharukaCkasthuri Make a modification here that caters for if the router node is already present but all the chat types are not. In the class we asked students to create a new chat type node for themselves and they struggled to add it.

2025-04-22 23:53 UTC, closed without merging

2025-04-22 23:53 UTC, marsninja commented
Outdated.