[REFACTOR]: Migrate all process to pluggy
Jaseci-Labs/jaseci pull request #1316
Opened 2024-09-26 15:45 UTC by amadolid

## **Description**

2024-10-01 16:02 UTC, ypkang requested changes
Let's make the neccessary changes on jac-cloud too so main would work post-merge.

2024-10-01 16:02 UTC, ypkang commented on jac/jaclang/plugin/default.py
> +        # Jac.Walker = WalkerArchitype
Remove this and add a `pass`

2024-10-01 16:02 UTC, ypkang commented on jac/jaclang/plugin/default.py
> +    def spawn_call(op1: Architype, op2: Architype) -> WalkerArchitype:
walker should be spawned on the target node of the edge, instead of the source.

2024-10-01 16:02 UTC, ypkang commented on jac/jaclang/plugin/tests/fixtures/other_root_access.jac
> +            Jac.unrestrict(here.__jac__, self.level);
Permission methods shoudl accept architype instead of anchors.

2024-10-01 18:40 UTC, ypkang commented on jac-cloud/jac_cloud/core/architype.py
> +        from jaclang.plugin.feature import JacFeature as Jac
is inline import neccessary?

2024-10-01 18:51 UTC, ypkang commented on jac-cloud/jac_cloud/core/architype.py
> +    def __init__(self) -> None:
Why does this need to change?

2024-10-01 18:59 UTC, ypkang commented on jac-cloud/jac_cloud/plugin/jaseci.py
> +        architype: Architype, root_id: BaseAnchor, level: AccessLevel | int | str
Need to understand why `root_id` is BaseAnchor here.

2024-10-02 16:33 UTC, ypkang submitted a review, later dismissed

2024-10-02 16:33 UTC, ypkang commented on jac-cloud/jac_cloud/core/architype.py
> +        from jaclang.plugin.feature import JacFeature as Jac
Seems like we won't need inline import here anymore.

2024-10-02 16:33 UTC, ypkang commented on jac-cloud/jac_cloud/plugin/jaseci.py
> +        if FastAPI.enable():
is_enabled()

2024-10-07 15:25 UTC, ypkang commented
@marsninja please take a look at this PR. The main change here is to move most of the functionality of anchor classes as plugin methods. I have reviewed this and am okay with the changes.

2024-10-08 14:20 UTC, marsninja approved these changes

2024-10-08 14:21 UTC, merged