[WIP] JAC Cloud Orchestrator
Jaseci-Labs/jaseci pull request #1319
Opened 2024-09-27 15:34 UTC by AshishMahendra

## **Description**
JAC Cloud Orchestrator is designed to dynamically import any Python module, deploy it as a Kubernetes Pod, and expose it as an independent gRPC service. This enables any Python module to be a microservice, providing flexibility and scalability in a cloud environment.

2024-10-03 10:21 UTC, AshishMahendra commented
Hi, @marsninja, can you please share your thoughts on the approach, i have added a readme for reference

2024-10-04 00:30 UTC, marsninja commented
Good start @AshishMahendra, Some of this implementation looks relevant to the final approach. 

For the first version of jac-cloud-orc (which by the way im thinking if jac-splice-orc might be better) would be the following: 

- A plugin that overrides jac_import to add capability that will automatically turn particular named modules into remote containerized kubernetes pod services that the importing modules would send all interactions to
- Initially these modules can be specified in a config file or through the settings.py interface
- This plugin would use the kubernetes python client library to automatically detect whether these running jac application is in a kubernetes environment and has the right permissions to create pods in that environment (this was prototyped in jaseci 1 and is do-able)
- The plugin would automatically generate the relevant manifests through the k8s protocol to start the pod and initially stall until the pod was ready, then the rest of the module can then execute. 

Basically it would be something like that, i'd want as much automatic control being done by splice-orc as possible.

2024-10-15 12:51 UTC, marsninja commented
Hi @AshishMahendra I see you've assigned this to me. What feedback do you want?

2024-10-16 07:50 UTC, AshishMahendra commented
Hi @marsninja, we have a version ready, as per your suggestions, so wanted your feedback

2024-11-06 14:04 UTC, marsninja requested changes

2024-11-06 14:04 UTC, marsninja commented on jac-splice-orc/MANIFEST.in
> +include managers/pod_manager_deployment.yml
Dont think we need this.

2024-11-06 14:04 UTC, marsninja commented on jac-splice-orc/jac_splice_orc/Dockerfile
> +# Use a single base image
Add some description how its used.

2024-11-06 14:04 UTC, marsninja commented on jac-splice-orc/jac_splice_orc/managers/pod_manager.py
> +            return f"Error executing kubectl command: {e}"
Seems like this needs to be removed.

2024-11-06 14:04 UTC, marsninja commented on jac-splice-orc/jac_splice_orc/managers/pod_manager.py
> +        )
prints need to be logger across hte board

2024-11-06 14:04 UTC, marsninja commented on jac-splice-orc/jac_splice_orc/managers/pod_manager_deployment.yml
> +        - name: SERVICE_TYPE
Dictionaryize, and make naming and selections as config file based.

2024-11-06 14:04 UTC, marsninja commented on jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py
> +        self.configure_pod_manager_url(namespace)
Make this not a constructor but just a class method that you call directly, and have it be called by a cli command instead of the deploy.py

2024-11-06 14:04 UTC, marsninja commented on jac/jaclang/settings.py
> +                "lib_cpu_req": "500m",
there should be no changes to this file.

2024-11-07 12:37 UTC, AshishMahendra commented on jac-splice-orc/MANIFEST.in
> +include managers/pod_manager_deployment.yml
removed

2024-11-07 12:38 UTC, AshishMahendra commented on jac-splice-orc/jac_splice_orc/managers/pod_manager.py
> +            return f"Error executing kubectl command: {e}"
removed

2024-11-07 12:42 UTC, AshishMahendra commented on jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py
> +        self.configure_pod_manager_url(namespace)
Done, created a command call orc_initialize

2024-11-07 15:08 UTC, AshishMahendra commented on jac/jaclang/settings.py
> +                "lib_cpu_req": "500m",
Removed the changes

2024-11-07 16:14 UTC, AshishMahendra commented on jac-splice-orc/jac_splice_orc/managers/pod_manager.py
> +        )
changed

2024-11-07 17:00 UTC, AshishMahendra commented on jac-splice-orc/jac_splice_orc/Dockerfile
> +# Use a single base image
Added

2024-11-11 11:43 UTC, AshishMahendra commented on jac-splice-orc/jac_splice_orc/managers/pod_manager_deployment.yml
> +        - name: SERVICE_TYPE
completed

2024-11-11 14:44 UTC, marsninja approved these changes

2024-11-11 14:44 UTC, merged