[INPROGRESS][WEBHOOK]: Initial integration
Jaseci-Labs/jaseci pull request #1392
Opened 2024-10-18 13:17 UTC by amadolid

## **Description**

2024-10-30 13:18 UTC, amadolid commented
backup
https://github.com/amadolid/jaseci/tree/webhook-backup

2024-11-15 09:02 UTC, amadolid commented
REBASED

2024-11-15 18:35 UTC, ypkang commented
Update the specs options to include using header/path/body for the webhook authentication key.

2025-01-06 20:28 UTC, ypkang requested changes

2025-01-06 20:28 UTC, ypkang commented on jac-cloud/jac_cloud/jaseci/models/webhook.py
> +        You may override this if you wish to implement different structure
this needs to be updated.

2025-01-06 20:28 UTC, ypkang commented on jac-cloud/jac_cloud/tests/simple_graph.jac
> +walker webhook {
I'd change this to be named something else other than `webhook` to avoid confusion.

2025-01-06 20:29 UTC, ypkang commented
@amadolid Tested this and I have one question

What should the URL look like for the `path` option for the key? I tried `/webhook/walker/webhook/API_KEY_HERE` and doesn't seem to work.

Otherwise, this works as expected, resolve the conflict and the comments and I can merge this.

2025-01-07 08:24 UTC, amadolid commented
> @amadolid Tested this and I have one question
> 
> What should the URL look like for the `path` option for the key? I tried `/webhook/walker/webhook/API_KEY_HERE` and doesn't seem to work.
> 
> Otherwise, this works as expected, resolve the conflict and the comments and I can merge this.

Here's the sample webhook using path as auth

```python
walker webhook {
    can enter1 with `root entry {
        report here;
    }

    class __specs__ {
        has webhook: dict = {"type": "path", "name": "key"}, path: str = "/{key}";
    }
}
```

Here's how to call it
```bash
curl -X 'POST' \
  'http://localhost:8001/webhook/walker/webhook/676cf326532283bae2b574b5%3A1736237645%3AmnSMcWwdmdYD90rLyXUCBEDGFVHJEceR' \
  -H 'accept: application/json' \
  -d ''
```
![image](https://github.com/user-attachments/assets/5cb4ec03-6c43-425f-aca2-e6218574c623)

2025-01-07 14:28 UTC, ypkang commented
> > @amadolid Tested this and I have one question
> > What should the URL look like for the `path` option for the key? I tried `/webhook/walker/webhook/API_KEY_HERE` and doesn't seem to work.
> > Otherwise, this works as expected, resolve the conflict and the comments and I can merge this.
> 
> Here's the sample webhook using path as auth
> 
> ```python
> walker webhook {
>     can enter1 with `root entry {
>         report here;
>     }
> 
>     class __specs__ {
>         has webhook: dict = {"type": "path", "name": "key"}, path: str = "/{key}";
>     }
> }
> ```
> 
> Here's how to call it
> 
> ```shell
> curl -X 'POST' \
>   'http://localhost:8001/webhook/walker/webhook/676cf326532283bae2b574b5%3A1736237645%3AmnSMcWwdmdYD90rLyXUCBEDGFVHJEceR' \
>   -H 'accept: application/json' \
>   -d ''
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/74129725/400690946-5cb4ec03-6c43-425f-aca2-e6218574c623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNTg3MDYsIm5iZiI6MTczNjI1ODQwNiwicGF0aCI6Ii83NDEyOTcyNS80MDA2OTA5NDYtNWNiNGVjMDMtNmM0My00MjVmLWFjYTItZTYyMTg1NzRjNjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDE0MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YThlNmUyMTU4MGY1NzJkZjA2Mzk5Y2MzYzJhZDcwOGVkODk2MGEwZDQxZWZkZTQ2MDBlMGI1NTBhNTQ0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9lYY6AeeOfDsnVBwcGT2aC0MrrOrrVc_n9ZPnwTDQDE)

I see. We need to document this. Can you add one example each for each type (header/path/query/payload) just like what you did here and include it in the documentation?

2025-01-07 19:08 UTC, ypkang approved these changes
Good to merge this one. I'd like someone to use this to validate it covers the common use case.

@ChrisIsKing i think you were trying to use webhook for a messaging platform integration right? Could you take this for a spin?

2025-01-07 19:09 UTC, merged