[INPROGRESS][WEBSOCKET]: Initial Implementation
Jaseci-Labs/jaseci pull request #1415
Opened 2024-10-31 09:17 UTC by amadolid

## **Description**

2024-11-04 08:23 UTC, amadolid commented
BACKUP
https://github.com/amadolid/jaseci/tree/websocket-backup

2024-11-04 08:41 UTC, amadolid commented
Will continue to upgrade to support channels using
https://github.com/encode/broadcaster

2024-11-15 08:53 UTC, amadolid commented
REBASED

2025-01-06 19:11 UTC, ypkang commented
@amadolid I tested this and have some question:

1. How do we set up a server-side walker that listens on a connected web socket and continuously receive data from it? For example, something like this
```
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message text was: {data}")
```

2. Does the notify_user/channel/client accept string or does it have to be json? The example above is just sending a string via `send_text`

2025-01-06 19:19 UTC, ypkang commented
Also, I think we are going to need a different type of documentation on this. We need to include end-to-end examples, like what fastAPI has https://fastapi.tiangolo.com/advanced/websockets/#await-for-messages-and-send-messages.

We need maybe 3 common use case:
1. A user establishing a connection with server and continuously exchanging messages
2. Multiple users (unauth) establish connections via a specific channel id and listening on messages. An authenticated user broadcast a message to the channel via restAPI call.
3. A user establish WS connections with multiple clients. Server send messages to one or many clients.

2025-01-06 19:31 UTC, ypkang requested changes

2025-01-06 19:31 UTC, ypkang commented on jac-cloud/jac_cloud/tests/jac-cloud-websocket.insomnia
I don't think we should commit the insomnia collection.

2025-01-06 19:31 UTC, ypkang commented on jac-cloud/jac_cloud/jaseci/security/__init__.py
> +        token = authorization[7:]
a nitpick: I'd use `len("bearer")` instead of `7`. A bit more readable.

2025-01-06 19:31 UTC, ypkang commented on jac-cloud/jac_cloud/tests/runner.py
> +"""Sample Runner."""
Hmm is this a helper script? do we need to commit this?

2025-01-07 07:54 UTC, amadolid commented
> Also, I think we are going to need a different type of documentation on this. We need to include end-to-end examples, like what fastAPI has https://fastapi.tiangolo.com/advanced/websockets/#await-for-messages-and-send-messages.
> 
> We need maybe 3 common use case:
> 
>     1. A user establishing a connection with server and continuously exchanging messages
> 
>     2. Multiple users (unauth) establish connections via a specific channel id and listening on messages. An authenticated user broadcast a message to the channel via restAPI call.
> 
>     3. A user establish WS connections with multiple clients. Server send messages to one or many clients.

Agree, tho the sample insomnia export has the complete use case including the request examples. Might need to convert it to docs type

2025-01-07 14:29 UTC, ypkang commented
> > Also, I think we are going to need a different type of documentation on this. We need to include end-to-end examples, like what fastAPI has https://fastapi.tiangolo.com/advanced/websockets/#await-for-messages-and-send-messages.
> > We need maybe 3 common use case:
> > ```
> > 1. A user establishing a connection with server and continuously exchanging messages
> > 
> > 2. Multiple users (unauth) establish connections via a specific channel id and listening on messages. An authenticated user broadcast a message to the channel via restAPI call.
> > 
> > 3. A user establish WS connections with multiple clients. Server send messages to one or many clients.
> > ```
> 
> Agree, tho the sample insomnia export has the complete use case including the request examples. Might need to convert it to docs type

Yeah but the insomnia doesn't include the server side implementation.

2025-01-07 15:49 UTC, amadolid commented on jac-cloud/jac_cloud/tests/runner.py
> +"""Sample Runner."""
This might be good example for deploying using uvicorn

2025-01-20 15:05 UTC, ypkang commented on jac-cloud/jac_cloud/tests/jac-cloud-websocket.insomnia
> +_type: export
@amadolid lets not commit this. I think it is a good reference but i don't know if it belongs to the repo. You can upload it somewhere else (e.g. google drive) and add a link to it in the docs.

2025-01-20 15:06 UTC, ypkang commented on jac-cloud/setup.py
> +        "broadcaster[redis]~=0.3.1",
Does websocket work with fake-redis?

2025-01-21 14:00 UTC, amadolid commented on jac-cloud/setup.py
> +        "broadcaster[redis]~=0.3.1",
No, since it's only in runtime memory

2025-01-21 14:01 UTC, amadolid commented on jac-cloud/jac_cloud/tests/jac-cloud-websocket.insomnia
> +_type: export
will update

2025-01-22 15:55 UTC, ypkang approved these changes

2025-01-22 15:57 UTC, ypkang commented
I am okay with merging this @amadolid. I'd like us to do some serious testing with websockets. I know zsb uses it and we are starting to migrate it to jaclang so maybe we can start with the streaming part of the implementation. Let's discuss @amadolid @asimsalim

2025-01-22 15:59 UTC, merged