Added new Documentation Outline
Jaseci-Labs/jaseci pull request #215
Opened 2022-04-20 13:57 UTC by king-mango

All changes are found within the docs/docs folder .

2022-04-20 13:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Jaseci-Labs/jaseci?pullRequest=215) <br/>All committers have signed the CLA.

2022-04-21 10:06 UTC, marsninja requested changes
Based on chat yesterday lets use Markdown throughout to be consistent, and i think we can remove the package files.

2022-04-21 12:08 UTC, king-mango commented
Noted , Dr.Mars.

Yours  respectfully,
 Timothy Shiwprasad

On Thu, Apr 21, 2022, 6:06 AM Jason Mars ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Based on chat yesterday lets use Markdown throughout to be consistent, and
> i think we can remove the package files.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Jaseci-Labs/jaseci/pull/215#pullrequestreview-948377174>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALCN7X6NEJZ3ADAVBROZXVDVGESCHANCNFSM5T4EPOUQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-28 10:27 UTC, marsninja approved these changes
LGTM! :-D

2022-04-28 10:27 UTC, merged