test cases updated
Jaseci-Labs/jaseci pull request #278
Opened 2022-05-17 09:23 UTC by AshishMahendra

## Describe your changes
created test cases for :
1. fasttext
2.  summarization(cl_summer)
3. text segmenter
4. Use Enc
5. Use QA
## Link to related issue
N/A
## Does this introduce new feature or change existing feature of Jaseci? If so, please add tests.
N/A
## Will this impact Jaseci users? If so, please write a paragraph describing the impact.
N/A
## Anything in this PR should the Jaseci developer/contributor community pay particular attention to? If so, please describe.
N/A

2022-05-18 20:34 UTC, ypkang requested changes
@AshishMahendra as mentioned on the other PR #258 , we figured out a solution that doesn't require modifying sys.path. Let's adopt that and update it for the test cases here.

2022-05-18 20:35 UTC, ypkang requested changes

2022-05-18 20:35 UTC, ypkang commented on jaseci_kit/jaseci_kit/modules/fasttext/tests/test_fast_enc.py
> +import os
let's make sure not import packages that are not being used. I don't think `os` is used in here.

2022-05-20 12:11 UTC, AshishMahendra commented
@ypkang I have updated and checked the testing for all modules, findings:
1. t5_sum has some error while testing which i didn't deep dive ( it would be helpful is Shawn can have a look)
2. I wasn't able to run all at once as my system ran out of memory  
3. I have updated bi.py and entity extraction for config files import issue

2022-05-21 20:24 UTC, ypkang commented
@AshishMahendra some of the biencoder and NER tests are still failing. I updated the test.sh in jaseci_kit. That script will run everything. We should look at these failure together.

2022-05-21 20:24 UTC, ypkang requested changes
some of biencoder and ner tests are still failing.

2022-05-24 01:22 UTC, ypkang commented
1, confirm that click version misamtch is the issue and come up with somlution to upgrade/downgrade one
2. add a quick fastapi based test for t5_sum

3. fix t5_sum import path issue

2022-05-25 00:03 UTC, ypkang approved these changes

2022-05-25 00:04 UTC, merged