Version substitute in jaseci kit
Jaseci-Labs/jaseci pull request #305
Opened 2022-06-12 19:24 UTC by ashagraw91

## Describe your changes

Make use of version number for github for jaseci KIT and substitute specif version number

## Link to related issue
https://app.clickup.com/t/2dtqwpf

## Does this introduce a new feature or change the existing feature of Jaseci? If so, please add tests.
yes

## Will this impact Jaseci users? If so, please write a paragraph describing the impact.
Should have no impact

## Anything in this PR should the Jaseci developer/contributor community pay particular attention to? If so, please describe.

The versioning of the jaseci KIT while deployments

2022-06-13 12:05 UTC, asimsalim requested changes
@ashagraw91  Can we create new yaml files as discussed ?
It can be in the format use_enc.prod.yaml 
This is also required for Jaseci.yaml

2022-06-13 14:46 UTC, ypkang commented
@asimsalim @ashagraw91 I like this change. Just curious -- what is the original problem/use case that lead to this change? 
And, yea I agree it would be good to keep the option of installing from source.

2022-06-14 11:52 UTC, marsninja commented
@ypkang Have a quick look at this pr and lets discuss.

2022-06-14 20:09 UTC, ashagraw91 commented
@ypkang this change is because the new implementation requires specific version of jaseci kit to be deployed in a pod, keeping it latest breaks changes if there has been a major update in kit model. the version helps in keeping in the stable model for ai pods

2022-06-14 20:36 UTC, ashagraw91 commented
@asimsalim I have updated for use_qa and use_enc. jaseci willnot need to change as the pod Ip for both will same for jaseci pod. Also let me know if other yamls also need to be updated?

2022-06-16 22:27 UTC, ypkang approved these changes
This looks good to me.

2022-07-21 19:27 UTC, marsninja approved these changes
LGTM

2022-07-21 19:27 UTC, marsninja commented on jaseci_kit/jaseci_kit/modules/use_enc/README.md
> +export version= {version no}  i.e 1.3.3.16
@ashagraw91 I'd use a bit more specific env var like "jskit_version" throughout

2022-07-21 19:28 UTC, marsninja approved these changes
LGTM

2022-07-21 19:28 UTC, merged