Mlflow_tfm_ner_testcase
Jaseci-Labs/jaseci pull request #339
Opened 2022-07-25 03:43 UTC by SatyamRajawat

## Describe your changes

## Link to related issue

## Does this introduce new feature or change existing feature of Jaseci? If so, please add tests.

## Will this impact Jaseci users? If so, please write a paragraph describing the impact.

## Anything in this PR should the Jaseci developer/contributor community pay particular attention to? If so, please describe.

2022-07-25 03:43 UTC, SatyamRajawat commented
Hi @AshishMahendra , Please review it.

2022-07-26 16:36 UTC, AshishMahendra reviewed
Let's Merge the changes, I'll have to update the test file to use the old testing set. I can create a PR once this is merged

2022-08-03 17:02 UTC, ypkang requested changes
@AshishMahendra I just realized that I never actually submitted my review comments on this one...here they are. 

Can you do the same thing as you did with the biencoder one -- copy the code to your fork so we can make changes if we need?

2022-08-03 17:02 UTC, ypkang commented on jaseci_kit/jaseci_kit/modules/tfm_ner/tfm_ner.py
> +from train import (
@AshishMahendra Does this actually work? I remember we had to set the importing to be relative with the `.` to get the deployment options working. Did you test this through all the deployment options, including `kubectl apply -f tfm_ner.yaml` and actions load local/module/remote?

2022-08-03 17:02 UTC, ypkang commented on jaseci_kit/jaseci_kit/modules/tfm_ner/tfm_ner.py
> +from entity_utils import create_data, create_data_new
same here.

2022-08-03 17:02 UTC, ypkang commented on jaseci_kit/jaseci_kit/modules/tfm_ner/tfm_ner.py
> +    # staging_model_path = model_config["staging_model_path"]
Let's not have any commented out code block in the code base. If they are not needed, delete the code. If they should be kept around for some reason, leave a comment describing why.

2022-08-03 17:02 UTC, ypkang commented on jaseci_kit/jaseci_kit/modules/tfm_ner/train.py
> +def start_model_training(
I am still curious why these functions are renamed. Do we know why?

2022-08-03 17:02 UTC, ypkang commented on jaseci_kit/jaseci_kit/modules/tfm_ner/train.py
> +    # ###################### testing started ##########################
I am not a fun of these type of comment in the code. It should just be a normal comment `# Testing started.`

2022-08-03 17:42 UTC, ypkang commented
Replaced by #359

2022-08-03 17:42 UTC, closed without merging