Template and automate the process of creating a new AI service
Jaseci-Labs/jaseci pull request #57
Opened 2021-11-16 22:16 UTC by ypkang

2021-11-16 22:19 UTC, ypkang commented
@marsninja let me know what you think of this. It is not much real "templating" but more so just to save manual copy/past/search and replace required for adding a new AI model.

If you have other ideas on how we can template this better, I am definitely open to it!

2021-11-17 16:14 UTC, ypkang commented
This is ready for review.

2021-12-01 14:19 UTC, marsninja requested changes
Hi Yipig, can you write a readme for the ai_serving directory that gives an overview of the approach?

2021-12-01 18:18 UTC, ypkang commented
> Hi Yipig, can you write a readme for the ai_serving directory that gives an overview of the approach?

@marsninja Added a simple README under `ai_serving/`

2021-12-02 13:38 UTC, marsninja requested changes

2021-12-02 13:38 UTC, marsninja commented on ai_serving/template/Dockerfile
> +FROM ubuntu:20.04
Can we try switching this to python:3-slim, thats what jaseci is based on these days and would save image size for public dockerhub. Give it a try , if too tricky we can keep ubuntu.

2021-12-02 21:39 UTC, merged