Walker documents
Jaseci-Labs/jaseci pull request #573
Opened 2022-11-02 05:16 UTC by TharukaCkasthuri

Updated walkers documentation.

2022-11-02 13:33 UTC, ypkang requested changes

2022-11-02 13:33 UTC, ypkang commented on support/guide/lang_docs/walkers.md
> +```
You can use
```
```jac
JAC CODE HERE
```
to have it be syntax highlighted in the documentation with Jac's syntax.

2022-11-02 13:34 UTC, ypkang commented
`jac dot` will run the `init` walker of the jac file and print back the graph in the DOT format. You can then use something like [GraphViz](https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0A%0A%20%20subgraph%20cluster_0%20%7B%0A%20%20%20%20style%3Dfilled%3B%0A%20%20%20%20color%3Dlightgrey%3B%0A%20%20%20%20node%20%5Bstyle%3Dfilled%2Ccolor%3Dwhite%5D%3B%0A%20%20%20%20a0%20-%3E%20a1%20-%3E%20a2%20-%3E%20a3%3B%0A%20%20%20%20label%20%3D%20%22process%20%231%22%3B%0A%20%20%7D%0A%0A%20%20subgraph%20cluster_1%20%7B%0A%20%20%20%20node%20%5Bstyle%3Dfilled%5D%3B%0A%20%20%20%20b0%20-%3E%20b1%20-%3E%20b2%20-%3E%20b3%3B%0A%20%20%20%20label%20%3D%20%22process%20%232%22%3B%0A%20%20%20%20color%3Dblue%0A%20%20%7D%0A%20%20start%20-%3E%20a0%3B%0A%20%20start%20-%3E%20b0%3B%0A%20%20a1%20-%3E%20b3%3B%0A%20%20b2%20-%3E%20a3%3B%0A%20%20a3%20-%3E%20a0%3B%0A%20%20a3%20-%3E%20end%3B%0A%20%20b3%20-%3E%20end%3B%0A%0A%20%20start%20%5Bshape%3DMdiamond%5D%3B%0A%20%20end%20%5Bshape%3DMsquare%5D%3B%0A%7D)  to visualize the graph.

2022-11-04 02:49 UTC, marsninja approved these changes
Nice @TharukaCkasthuri !! I'll make some tweaks after merging this to break it up into subsections.

2022-11-04 02:49 UTC, merged