updated jaseci_ai_kit readme
Jaseci-Labs/jaseci pull request #635
Opened 2022-11-29 09:57 UTC by TharukaCkasthuri

## Describe your changes

## Link to related issue

## Does this introduce new feature or change existing feature of Jaseci? If so, please add tests.

## Will this impact Jaseci users? If so, please write a paragraph describing the impact.

## Anything in this PR should the Jaseci developer/contributor community pay particular attention to? If so, please describe.

2022-11-29 14:09 UTC, ypkang requested changes

2022-11-29 14:09 UTC, ypkang commented on README.md
> -  - [Personalized Head](jaseci_ai_kit/jaseci_ai_kit/modules/ph/README.md)
revert this.

2022-11-29 14:39 UTC, TharukaCkasthuri commented on README.md
> -  - [Personalized Head](jaseci_ai_kit/jaseci_ai_kit/modules/ph/README.md)
done

2022-12-05 13:36 UTC, marsninja approved these changes

2022-12-05 13:36 UTC, marsninja commented on README.md
> -  - [Personalized Head](jaseci_ai_kit/jaseci_ai_kit/modules/ph/README.md)
Any reason this is being removed? Or was this an accident?

2022-12-05 13:37 UTC, merged