Add zlib functionalities
Jaseci-Labs/jaseci pull request #649
Opened 2022-12-05 16:50 UTC by apatel66

Added some zlib functions to the standard library (compress and decompress). Created associated tests as well.

2022-12-05 16:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Jaseci-Labs/jaseci?pullRequest=649) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Jaseci-Labs/jaseci?pullRequest=649) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Jaseci-Labs/jaseci?pullRequest=649) it.</sub>

2022-12-05 17:04 UTC, marsninja requested changes
Nice work @apatel66 , On change needed, the jac/jac_parse files changed is likely due to not running `black` before commiting, by simply typing `black .` it should reformat properly then you can push.

2022-12-05 21:50 UTC, apatel66 commented
> Nice work @apatel66 , On change needed, the jac/jac_parse files changed is likely due to not running `black` before commiting, by simply typing `black .` it should reformat properly then you can push.

Yep, that seemed to have worked. I only had the black formatter run whenever I saved a file in vscode, so I also added it to my terminal.

2022-12-06 12:47 UTC, marsninja approved these changes
LGTM! Thanks @apatel66 !

2022-12-06 22:16 UTC, merged