[WIP][JSORC]: JsOrc Module / Application Context
Jaseci-Labs/jaseci pull request #853
Opened 2023-01-26 13:20 UTC by amadolid

2023-02-13 09:04 UTC, amadolid commented
Documentations to be follow

@ypkang, would like to ask for your review as I have adjusted the ActionOptimizer too

2023-02-15 14:02 UTC, ypkang requested changes

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/__init__.py
> +__all__ = ["JsOrc", "JsOrcSettings"]
Is this so that we can import JSORC directly from the jaseci package at the top level?

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/actions/standard/tests/test_mail_lib.py
> +    @JsOrc.inject(services=["mail"])
What does inject do?

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/api/jsorc_api.py
> +    def load_yaml(self, files: list, namespace: str = None):
Any reason we don't want namespace to be default to `default`?

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/api/jsorc_api.py
> +        status = JsOrc.get("action_manager", ActionManager).get_actions_status(name)
What happens if JSORC is not enabled? We shouldn't return success: True if that's the case right?

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/jsorc.py
> +        Save the class in services options
I would like to document these concepts better. At this point, I can;'t really understand what is a service, repository or context in JSORC. @amadolid lets chat.

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/jsorc_settings.py
> +import os
I am not a big fan of this file. It is massive and going to be hard to update and deal with down the line. How about we separate each config into is JSON file and then load them in here?

2023-02-15 14:02 UTC, ypkang commented on jaseci_core/jaseci/svc/kube_svc.py
> +class KubeService(CommonService):
I don't know if kubernetes should be a service. Let's discuss.

2023-02-16 05:20 UTC, amadolid commented on jaseci_core/jaseci/__init__.py
> +__all__ = ["JsOrc", "JsOrcSettings"]
Yup and also JsOrc class would be one of the first classes to be loaded

2023-02-16 05:22 UTC, amadolid commented on jaseci_core/jaseci/actions/standard/tests/test_mail_lib.py
> +    @JsOrc.inject(services=["mail"])
upon calling that method mail (service) will be injected as keyword argument

2023-02-16 05:26 UTC, amadolid commented on jaseci_core/jaseci/api/jsorc_api.py
> +    def load_yaml(self, files: list, namespace: str = None):
kubeService now holds the namespace (defaults to "default").
If admin wants to override it, that's when they need to include namespace on load_yaml api

2023-02-16 06:34 UTC, amadolid commented on jaseci_core/jaseci/api/jsorc_api.py
> +        status = JsOrc.get("action_manager", ActionManager).get_actions_status(name)
JsOrc now cannot be disabled while action_manager is a context type which should return as demand (.get will reuse same instance). However, if the method call in action_manager has service connection like the kubeService it should raise exception and let jac view handle the exception

will add some adjustment on action_optimizer.kube_create/kube_delete

2023-02-16 06:35 UTC, amadolid commented on jaseci_core/jaseci/jsorc.py
> +        Save the class in services options
Yup yup, currently working on the documentation

2023-02-16 06:37 UTC, amadolid commented on jaseci_core/jaseci/jsorc_settings.py
> +import os
Yup, i'm planning to have a yaml parser as default for manifest config
JsOrcSettings:
 ELASTIC_MANIFEST = load_yaml("elastic.yaml") // should return the same

2023-02-16 06:39 UTC, amadolid commented on jaseci_core/jaseci/svc/kube_svc.py
> +class KubeService(CommonService):
The reason for this is to allow user change kubernetes connection configs (also ping test) on runtime

2023-02-16 10:18 UTC, amadolid commented on jaseci_core/jaseci/jsorc_settings.py
> +import os
Added the new load yaml from file

2023-02-16 13:29 UTC, ypkang commented on jaseci_core/jaseci/actions/standard/tests/test_mail_lib.py
> +    @JsOrc.inject(services=["mail"])
Let's remove inject.

2023-02-17 13:20 UTC, ypkang approved these changes
f

2023-02-17 13:21 UTC, merged