added complete code for canoniCAI
Jaseci-Labs/jaseci pull request #871
Opened 2023-01-31 12:43 UTC by TharukaCkasthuri

2023-02-01 13:55 UTC, ypkang requested changes
1, Let's rename the folder from canoni_chatbot to `reference`
2. tfm_ner.jac and bi_enc.jac are already in the repo. Let's not duplicate them.
3.

2023-02-04 07:30 UTC, AshishMahendra commented
> 1, Let's rename the folder from canoni_chatbot to `reference` 2. tfm_ner.jac and bi_enc.jac are already in the repo. Let's not duplicate them.

Code has be updated as per the request

2023-02-04 07:30 UTC, AshishMahendra approved these changes

2023-02-05 22:13 UTC, ypkang approved these changes

2023-02-05 22:13 UTC, merged