[PRELOAD-ACTIONS]: Add error handling
Jaseci-Labs/jaseci pull request #894
Opened 2023-02-07 09:12 UTC by amadolid

2023-02-07 22:46 UTC, ypkang commented
@amadolid When i run the test_module_async test locally, it fails
```
self = <jaseci.tests.test_progs.JacTests testMethod=test_module_on_async>

    def test_module_on_async(self):
        with open("jaseci/tests/fixtures/non_existing_action.py", "w") as file:
            file.write(
                "from jaseci.actions.live_actions import jaseci_action\n@jaseci_action(act_group=['sim1'])\ndef tester():\n\treturn 1"
            )

        mast = self.meta.build_super_master()
        mast._h.task.state = ServiceState.RUNNING
        mast.sentinel_register(name="test", code=jtp.async_module, auto_run="")

        # sequence is relevant
        mast.actions_load_local("jaseci/tests/fixtures/non_existing_action.py")
        mast.actions_load_local("jaseci/tests/fixtures/existing_action.py")

        res = mast.general_interface_to_api(
            api_name="walker_run",
            params={"name": "a", "ctx": {}},
        )

        self.assertTrue(res["success"])

        # will return [1,2] since all local actions are loaded on MainProcess
        self.assertEqual([1, 2], res["report"])

        os.remove("jaseci/tests/fixtures/non_existing_action.py")

        res = mast.general_interface_to_api(
            api_name="walker_run",
            params={"name": "b", "ctx": {}},
        )

>       self.assertTrue(res["is_queued"])
E       AssertionError: False is not true

jaseci/tests/test_progs.py:564: AssertionError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
Time: 0.008 - test_module_on_async: [failed]
```

2023-02-07 22:47 UTC, ypkang requested changes
See test failure above.

2023-02-08 06:10 UTC, amadolid commented
Hello @ypkang,

I have adjusted the unit test. You may try again

2023-02-08 13:54 UTC, ypkang approved these changes

2023-02-08 13:55 UTC, merged