Docs Architype Section Completed
Jaseci-Labs/jaseci pull request #969
Opened 2023-02-26 21:32 UTC by RolexAlexander

Good Afternoon Dr Mars and the Development Team. I completed the architype section of the docs and also added some more info to the language basics sections. Additionally, the plan for this week is to ensure all content from jaseci bible that belongs in the architype section is migrated to the docs along with the respective examples.

2023-02-27 21:48 UTC, ypkang requested changes

2023-02-27 21:48 UTC, ypkang commented on docs/docs/jaseci_architype/take.md
> +Lets change the `init` walker of **Example 3** to demostrate how the `skip` command works;
@RolexAlexander Does it make sense to be indexing the examples in the docs like this? `Example 3`. Is there an example 3 in the docs actually? If so, we should make the `Example 3` text a hyper link to it. If not, we should remove it. There are several places here.

2023-02-27 23:00 UTC, RolexAlexander commented
Good Night noted, I will make the changes.

On Mon, Feb 27, 2023 at 5:48 PM Yiping Kang ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/docs/jaseci_architype/take.md
> <https://github.com/Jaseci-Labs/jaseci/pull/969#discussion_r1119347704>:
>
> > @@ -0,0 +1,264 @@
> +## Skipping and Disengaging
> +
> +Jac offers couple of more useful control statements that are pretty convenient, `skip` and `disengage`, with walker traversing graphs with `take` commands.
> +
> +### Skipping
> +
> +The idea behind the abstraction of `skip` in the context of a walkers code block is that it tells a walker to halt and abandon any unfinished work on the current node in favor of moving to the next node (or complete computation if no nodes are queued up).
> +
> +> **Note**
> +>
> +> Node/edge abilities also support the usage of the skip directive. The skip merely decides not to use the remaining steps of that `ability` itself in this context.
> +
> +
> +Lets change the `init` walker of **Example 3** to demostrate how the `skip` command works;
>
> @RolexAlexander <https://github.com/RolexAlexander> Does it make sense to
> be indexing the examples in the docs like this? Example 3. Is there an
> example 3 in the docs actually? If so, we should make the Example 3 text
> a hyper link to it. If not, we should remove it. There are several places
> here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Jaseci-Labs/jaseci/pull/969#pullrequestreview-1316485613>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYLVMPILSVAEHJS5HJXLPVTWZUOLPANCNFSM6AAAAAAVIWATIY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-28 13:43 UTC, ypkang approved these changes

2023-02-28 13:43 UTC, merged